import { Product } from '@/types/product';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Monstera Deliciosa',
    slug: 'monstera-deliciosa',
    description: 'The iconic Swiss Cheese Plant, known for its dramatic fenestrated leaves.',
    price: 45.00,
    image_url: '/plants/monstera.jpg',
    category: 'Aroids',
    stock_quantity: 15,
    care_level: 'Moderate',
    sunlight: 'Bright Indirect',
    water_frequency: 'Every 1-2 weeks',
    indoor: true,
    is_pet_friendly: false,
  },
  {
    id: '2',
    name: 'Snake Plant',
    slug: 'snake-plant',
    description: 'An incredibly hardy plant that thrives on neglect and purifies the air.',
    price: 25.00,
    image_url: '/plants/snake-plant.jpg',
    category: 'Succulents',
    stock_quantity: 24,
    care_level: 'Easy',
    sunlight: 'Low to Bright Direct',
    water_frequency: 'Every 2-3 weeks',
    indoor: true,
    is_pet_friendly: false,
  },
  {
    id: '3',
    name: 'Fiddle Leaf Fig',
    slug: 'fiddle-leaf-fig',
    description: 'A popular indoor tree with large, violin-shaped leaves.',
    price: 85.00,
    image_url: '/plants/fiddle-leaf.jpg',
    category: 'Trees',
    stock_quantity: 8,
    care_level: 'Expert',
    sunlight: 'Bright Indirect',
    water_frequency: 'Weekly',
    indoor: true,
    is_pet_friendly: false,
  },
  {
    id: '4',
    name: 'Calathea Orbifolia',
    slug: 'calathea-orbifolia',
    description: 'Stunning oversized leaves with silver patterns. Loves humidity.',
    price: 38.00,
    image_url: '/plants/calathea.jpg',
    category: 'Calatheas',
    stock_quantity: 12,
    care_level: 'Moderate',
    sunlight: 'Medium Indirect',
    water_frequency: 'Weekly',
    indoor: true,
    is_pet_friendly: true,
  },
  {
    id: '5',
    name: 'Peace Lily',
    slug: 'peace-lily',
    description: 'Beautiful white spathes and deep green foliage. Great air purifier.',
    price: 30.00,
    image_url: '/plants/peace-lily.jpg',
    category: 'Flowering',
    stock_quantity: 20,
    care_level: 'Easy',
    sunlight: 'Medium Indirect',
    water_frequency: 'Weekly',
    indoor: true,
    is_pet_friendly: false,
  }
];
